travis:
  secure:
    BINSTAR_TOKEN: ytgDim0iA3WNgH/FrhUEwXA16xiFcLkqwY2RztBoBF0I39gqOlVAnuEgB1CNNxO3IxvGF0Aquo9cNmOcHpWwXmVH0vKMt6e9wJB0YVsHZ9tFXYvYptOOuS3DMHVaMdooZ94SzbaEK/69lGK1joGMhC3P9ck89So41odWSEG1oPA52GQS7UodzKJxOcsAhtQYHwUZl+B1byRd7asyuxZ9i5a8xb+fmGSFrvVSM656+G9yq8WyUCOApgdpKLTEAZub54j3DJYTPme9duGP6sC5giIdgIs50tw7xaQSSLmPvws4XIxSPCC2iqDMFci434D3oGC4fK2WzV1erzmSsBgemVURXy0wQSXpsmJ9ROoJ0TNsi4zXtRdI44po2+aegqSRtG2Dn2aDjim6pITejleGOFv0LSuBSH2RqjN3I6QKUWeJ3PX/7n1u0+MFs70VPAE5TIITA9+g6kNm4ass18eYXXuJKW3l+r6w4dS8WPUKWhT572CitcvtOezTnuZ5AV1X/UaPyBlTfu49DgcMa9YsfbaWUSt+07tjxuHDlceVO88Oypk1GcNnBQ1x50ihM4vVTX52WFLimgq0oRS92/U3dxaOXonfgBg/DefiMzEPNLeoO0n+/S+zpI+yFMyQZiP17Ld8BCLku3Z6Sx8i3kQAoenlSavh8rEX6j/DkTmWcIE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
