appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: T5MNqQeXJ7kUA5LyXSVsaSYUgu1xeYFl1bV13r6Nz/zaGw/Zl+yGlWtctUcbOM/+Y8bIO0foj8DKcfS+z8443IAI/sDpDz/27+7gkW0t6taStfJkPcbyqr5WF+l/tC2yzrheJpyQiyIlJ5lZoV4Nw3Cco//p5/HHkq/c2rZwpae2Iqg/pXkTJOmHfklEr6N2cbOHh5QaBpz2zuAv7rPAWiEmCZiKqYN6jZenU5qllH5devwpu3ghMKgDKZ7PczQ59Wa7v/GkUO3rP7dIdarOOu6s0jnuY8zd8r0F/lDPVExnDnLXD27wkfmclOmY3gFVYoBPrKbt3hN7AV9WdaGBFVU+u7STrCQEwKdsk/cnHw/hMux4emso+t4k6JXXlX7mk1PQNXsffFPbF955RdrYt+gMjGr7nFtUPabQHrspTrPHpdjrE8SAr6FfufoqK4P1BCuctnc3+hv3jwp0QUIL81jXizRnsF/7NlU34nnPqLJ1PzaDMTwZwcC2sywL2H0V0JgAo+QxA3PuUjxE2kjndrIMjc5f9nhOtIKWMFt8R9I7+WcBtIXlAhdlMN6/P60i6V0Z2/C+X6PyoUEBshSmY63r1sOqihtgYpeqHdrHxez47qKyRG+p2JtChdOXO0NZluinxaZssyJtbzmzLo28h8HZzJMuwKLta35jXs0VGPE=}
conda_forge_output_validation: true
